version: "3.9"
services:
  database:
    container_name: artworks-database-dev
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: always
    networks:
      - artworks-network
  backend:
    container_name: artworks-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ["./entrypoint_dev.sh"]
    ports:
     - 3000:3000
    environment:
      - RAILS_MASTER_KEY
    depends_on:
      database:
        condition: service_healthy
    restart: always
    networks:
      - artworks-network

networks:
  artworks-network:
    name: artworks-network
